# Generated by Django 4.1 on 2022-09-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200, verbose_name='Issue Name')),
                ('issue_date', models.DateTimeField(verbose_name='Issue Date')),
                ('issue_date_complete', models.DateTimeField(blank=True, verbose_name='Fixed Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('issue_id', models.CharField(max_length=999, verbose_name='Issue ID')),
                ('fixed_issue', models.BooleanField(blank=True, verbose_name='Fixed Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Project Name')),
                ('project_id', models.CharField(max_length=2, verbose_name='Project ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='Projected End Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
    ]
