# Generated by Django 4.1 on 2022-11-03 10:52

import bugtracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(blank=True, verbose_name='Issue Date')),
                ('issue_date_complete', models.DateField(blank=True, null=True, verbose_name='Fixed Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('issue_id', models.CharField(default=bugtracker.models.random_string, max_length=999999)),
                ('ticket_id', models.CharField(blank=True, max_length=9999999, unique=True, verbose_name='Ticket ID')),
                ('issue_fixed', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Fixed', 'Fixed'), ('On Hold', 'On Hold'), ('Duplicate', 'Duplicate')], default='Open', max_length=100, verbose_name='Ticket Progress')),
                ('fixed_comment', models.TextField(blank=True, verbose_name='Comment')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=60)),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Closed Date')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Project Name')),
                ('project_id', models.CharField(blank=True, default=bugtracker.models.random_id_string, max_length=3, unique=True, verbose_name='Project ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='Projected End Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Created')),
            ],
        ),
    ]
