# Generated by Django 4.1 on 2022-11-03 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.ManyToManyField(limit_choices_to={'groups__name__in': ['Project Leaders', 'Admin']}, related_name='project_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='working_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='closed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='fixed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='related_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bugtracker.project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='submitter',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
