# Generated by Django 4.1 on 2022-09-14 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugtracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='related_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bugtracker.project'),
        ),
    ]
