# Generated by Django 4.1 on 2022-09-19 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_lead',
            field=models.ManyToManyField(limit_choices_to={'groups__name__in': ['Project Leaders', 'Admin']}, related_name='project_lead', to=settings.AUTH_USER_MODEL),
        ),
    ]
