# Generated by Django 4.1 on 2022-09-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_role_customuser_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
